#ifndef SCHEDULER_H
#define SCHEDULER_H

#include <iostream>
#include <string>
#include <vector>
#include "ds/MaxHeap.h"
#include "ds/Queue.h"
#include "model/Flight.h"
#include "model/Runway.h"
using namespace std;

/*
    Scheduler
    ---------
    The brain of the airport.

    State it owns:
        - pending  : MaxHeap<Flight>  - all flights not yet cleared to a runway
        - runways  : vector<Runway>   - the physical runways
        - log      : Queue<Flight>    - completed flights, oldest first
        - currentTime                 - total simulation minutes elapsed

    What happens during one simulated minute (tick):
        1.  Every flight currently in the pending heap ages by one minute.
            Adding the same +1 to every priority preserves the heap order,
            so no rebuild is necessary -- O(n) total instead of O(n log n).
        2.  At most ONE flight is popped from the heap and dispatched to
            the least-loaded runway. This models real ATC clearance
            bandwidth: a controller can only clear one aircraft per minute.
        3.  Every runway ticks by 1 minute, possibly completing the
            flight it was serving and possibly starting the next from
            its queue.
        4.  Each runway's "completed during this tick" queue is drained
            into the global flight log.
        5.  currentTime is incremented.

    Per-tick cost summary:
        O(n)        ageing every pending flight
        O(log n)    one heap pop
        O(R)        ticking R runways and draining their completion queues

        Total      : O(n + R)

    Limitations to disclose in viva:
        - declareEmergency() only inspects the pending heap. A flight
          that has already been cleared into a runway's waiting queue
          cannot have its emergency status changed mid-flight in this
          version. (Promoting one would require exposing internal queue
          access on Runway, which we deliberately avoided.)
*/

class Scheduler {
private:
    MaxHeap<Flight> pending;
    vector<Runway>  runways;
    Queue<Flight>   log;
    int             currentTime;

    // Returns the index of the runway with the smallest "load",
    // where load = waiting queue size + (busy ? remaining minutes : 0).
    // Ties are broken by preferring the lowest-indexed runway.
    int pickRunway() const;

public:
    Scheduler();

    void addRunway(string name, int serviceTime);
    int  runwayCount() const;
    const Runway& getRunway(int index) const;

    int getCurrentTime()  const;
    int getPendingCount() const;
    int getLogSize()      const;

    void registerFlight(Flight f);

    // Returns true if a pending flight with this number was found and
    // upgraded to emergency status; false otherwise.
    bool declareEmergency(string flightNumber);

    // Convenience: peek the most-urgent pending flight without removing it.
    // Returns a default Flight if pending is empty.
    Flight peekPendingTop() const;

    // Advance the simulation by `minutes` (must be >= 0).
    void tick(int minutes);

    // Flight log helpers (FIFO: oldest completion first).
    bool   logEmpty() const;
    Flight peekLog()  const;
    Flight popLog();

    // Human-readable status block used by the CLI.
    string statusReport() const;

    // Lists every pending flight in pop order (most-urgent first).
    // Internally this works on a deep copy of the heap so the live
    // heap is not disturbed -- the copy constructors of MaxHeap and
    // Flight (auto-generated by the compiler over our vector member)
    // do all the work.
    string pendingListString() const;

    // Lists every flight in the log in FIFO order (oldest first),
    // again on a deep copy (Queue<T>'s Rule-of-Three copy constructor).
    string logListString() const;
};

#endif
